DROP TABLE IF EXISTS test;

CREATE TABLE IF NOT EXISTS test (id BIGINT NOT NULL, PRIMARY KEY (id));

INSERT INTO test (id) VALUES (1);
INSERT INTO test (id) VALUES (2);
INSERT INTO test (id) VALUES (3);
INSERT INTO test (id) VALUES (4);
